const type = {
    SET_PARTICIPANTS_COMPETITION_CATEGORY_MODALITY: 'SET_PARTICIPANTS_COMPETITION_CATEGORY_MODALITY',
    GET_ALL_ROUND_HEATS: 'GET_ALL_ROUND_HEATS',
    GET_ROUND_HEAT_DETAILS: 'GET_ROUND_HEAT_DETAILS',
    GET_ALL_HOME_ROUND_HEATS: 'GET_ALL_HOME_ROUND_HEATS',
}

export default type;