const type = {
    GET_CATEGORY_MODALITY_WITH_PART: 'GET_CATEGORY_MODALITY_WITH_PART',
    SET_PARTICIPANTS_COMPETITION_CATEGORY_MODALITY: 'SET_PARTICIPANTS_COMPETITION_CATEGORY_MODALITY',
    SET_PARTICIPANTS_AFTER_UNREGIST: 'SET_PARTICIPANTS_AFTER_UNREGIST',
    GET_ALL_ROUND_HEATS: 'GET_ALL_ROUND_HEATS',
    GET_ROUND_HEAT_DETAILS: 'GET_ROUND_HEAT_DETAILS',
    GET_ALL_HOME_ROUND_HEATS: 'GET_ALL_HOME_ROUND_HEATS',
}

export default type;